### ISSUE TITLE
Get away from MacVim

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/dotfiles#4]
right now I'm using MacVim in the terminal, which seems dumb. The only reason I'm using it is for clipboard support and I'm like 99% sure I can just get that by passing a flag to `brew install`.

Using MacVim in the terminal as my default editor also causes a fair number of issues because you can't set `$EDITOR` to `mvim -v` in zsh.

**Comment by gabebw** [comment]
I have clipboard support without MacVim, stock `brew install vim`: https://github.com/gabebw/dotfiles/blob/6d8000d8c69c416ebfab8788b142f8f7c835c71d/vim/options.vim#L14-L15

Kachow.

(Using it in tmux might require the `reattach-to-user-namespace` but who knows.)

**Comment by gfontenot** [comment]
![oh word?](http://dl.dropboxusercontent.com/u/452364/gifs/word.gif)

**Comment by gabebw** [comment]
Perfect GIF usage, as usual.
