### ISSUE TITLE
Add current Xcode information to tux status bar

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/dotfiles#7]
Right now, I'm adding `BETA` to my `RPROMPT` if have used `xcode-select` to set the Xcode command line tools to a different version, but it'd be really nice to have better output in a persistent state. Ideally, something like `Xcode 7.0` would probably be best.

**Comment by gfontenot** [comment]
So I can do this simply enough by running `xcodebuild -version | grep 'Xcode'`. The question becomes: how often does this command get run? Seems insane to run this constantly throughout the day. Maybe I should make a wrapper for `xcode-select` that updates this?

@christoomey is this going to crush my machine?

**Comment by christoomey** [comment]
The command looks speedy enough, so I don't think you should have any issue. The default refresh for the status bar is every 15 seconds, but you can change this with the `status-interval` option (although I don't think you'd need to).

I'd stick with the nice simple grep.

**Comment by gfontenot** [comment]
:+1: Added in ccfb234506cce92aba154b3464a3c09bc6183842. Thanks, Chris!
