### ISSUE TITLE
Make Brewfile dynamic

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/dotfiles#9]
the new brewfile format is, I believe, a ruby file. So it _might_ be possible to write it in a way where I can have tag-specific brewfiles and source them all into a central `brewfile` to use with `brew bundle`

**Comment by gabebw** [comment]
It is a Ruby file.

**Comment by gfontenot** [comment]
This doesn't actually work. But I _can_ just source the individual files. I've done this now in 09ba119bd1f1d5eb9d605740944028bee0b3e1cd

**Comment by gfontenot** [comment]
source them with brew bundle I mean.
